import { useTasks } from "../hooks/useData";
import { useSearchParams } from "react-router-dom";
import { useState } from "react";
export default function TasksPage() {
  const { tasks, loading, addTask, updateTask, deleteTask } = useTasks();
  const [searchParams] = useSearchParams(); const clientId = Number(searchParams.get("client")) || undefined;
  const [title, setTitle] = useState(""); const [status, setStatus] = useState("pending"); const [dueDate, setDueDate] = useState("");
  const handleAdd = async (e: React.FormEvent) => { e.preventDefault(); if (!title.trim()) return; await addTask({ title, status, due_date: dueDate || null, client_id: clientId }); setTitle(""); setStatus("pending"); setDueDate(""); };
  const toggleStatus = async (task: any) => { const next = task.status === "pending" ? "in_progress" : task.status === "in_progress" ? "completed" : "pending"; await updateTask(task.id, { status: next }); };
  return <div style={{ maxWidth: 900, margin: "0 auto", padding: 20 }}><h1>Task{clientId ? ` (Cliente #${clientId})` : ""}</h1><form onSubmit={handleAdd} style={{ display: "flex", gap: 8, marginBottom: 20, flexWrap: "wrap" }}><input placeholder="Titolo*" value={title} onChange={e => setTitle(e.target.value)} required /><select value={status} onChange={e => setStatus(e.target.value)}><option value="pending">Pending</option><option value="in_progress">In Corso</option><option value="completed">Completato</option></select><input type="date" value={dueDate} onChange={e => setDueDate(e.target.value)} /><button type="submit">Aggiungi</button></form>{loading && <p>Caricamento...</p>}<table style={{ width: "100%", borderCollapse: "collapse" }}><thead><tr style={{ background: "#eee" }}><th style={{ padding: 8 }}>Titolo</th><th style={{ padding: 8 }}>Stato</th><th style={{ padding: 8 }}>Scadenza</th><th style={{ padding: 8 }}>Cliente</th><th style={{ padding: 8 }}>Azioni</th></tr></thead><tbody>{tasks.map((t: any) => <tr key={t.id} style={{ borderBottom: "1px solid #ddd" }}><td style={{ padding: 8 }}>{t.title}</td><td style={{ padding: 8 }}>{t.status}</td><td style={{ padding: 8 }}>{t.due_date}</td><td style={{ padding: 8 }}>{t.client_name}</td><td style={{ padding: 8 }}><button onClick={() => toggleStatus(t)}>Cambia</button><button onClick={() => deleteTask(t.id)} style={{ marginLeft: 4 }}>Elimina</button></td></tr>)}</tbody></table></div>;
}
